  name: "Nextjs app Setup in AWS"
  
  on:
    workflow_dispatch:

  jobs:
    stack-initialization:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Creating nextjs sample application and deploying to aws s3"
        - name: checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false
        
        - name: use node.js v14 
          uses: actions/setup-node@v1
          with:
            node-version: '14'
            registry-url: https://registry.npmjs.org/

        - name: Stacks framework code generation
          run: |
            npx create-next-app nextjs-scaffold --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
            cp -r nextjs-scaffold/* .
            rm -rf nextjs-scaffold
            
        - name: Configure git
          run: |
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git remote set-url origin https://${{ github.actor }}:${{  secrets.GH_PAT  }}@github.com/${{ github.repository }}.git
            
        - name: Commit generated code and initialize workflows
          run: |
            git add .
            git commit -m "Generate framework code and initialize workflows"
            git push origin -u main